### PR TITLE
update to 0.1.2

### PR DESCRIPTION
**Pull request by mariinkys**

### CODE REVIEW

**Comment by mariinkys** [comment]
Seems like you still can't have the COSMIC category in metadata so this will be in hold until that can be added

**Comment by bbhtt** [comment]
you can make a PR to https://gitlab.freedesktop.org/xdg/xdg-specs to make it a valid category although appstream filters all DE names as categories, so it won't really help you.

You can put it as a keyword, as they can be arbitrary.

**Comment by mariinkys** [comment]
This change was made by one of the COSMIC developers themselves on a PR so I suppose they're already aware of this, as this is not the only app where this changes are being made.

PR: https://github.com/mariinkys/starrydex/pull/3#issuecomment-2379840679
Original Issue: https://github.com/pop-os/cosmic-store/issues/167
Other app with same commit: https://github.com/cosmic-utils/tasks/commit/832961e32d0867fd2a03d582637d2903c745b176

**Comment by bbhtt** [comment]
Looks like it was added to xdg specs last month but the list in appstream is not synced.

Anyways I commented on the PR.

**Comment by mariinkys** [comment]
I'm closing this PR since I will be publishing another update that fixes this issue and adds more features.

**Pull request closed without merging**
